image: php:8.3.4-cli  # Use the PHP 8.3.4 CLI image

definitions:
  caches:
    composer: ~/.composer/cache
    vendor: ./vendor
    node_modules: ./node_modules

steps:
  - step: &install
      name: 'Install dependencies'
      caches:
        - composer
        - vendor
        - node_modules
      script:
        # Install Composer dependencies
        - apt-get update && apt-get install -y unzip
        - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
        - composer install --no-interaction --no-progress --optimize-autoloader
        
        # Install Node.js dependencies if using Laravel Mix
        - curl -sL https://deb.nodesource.com/setup_14.x | bash -
        - apt-get install -y nodejs
        - npm install
        
  - step: &test
      name: 'Run tests'
      script:
        - php artisan test

  - step: &deploy
      name: 'Deploy to production'
      deployment: Production
      script:
        - echo "Deploying to production environment"
        - pipe: atlassian/ssh-run:0.4.1
          variables:
            SSH_USER: $SSH_USER
            SERVER: $SSH_SERVER
            MODE: 'script'
            COMMAND: 'php artisan down && ./scripts/deploy.sh && php artisan up'
          
pipelines:
  branches:
    development:
      - step: *install
      - step: *test
    production:
      - step: *deploy
